// src/lib/constants/home.data.ts

export const HERO_BANNERS = [
  { label: "Internships",  href: "#internships",  emoji: "💼", bg: "bg-blue-100"   },
  { label: "Jobs",         href: "#jobs",         emoji: "🧳", bg: "bg-slate-200"  },
  { label: "Hackathons",   href: "#hackathons",   emoji: "🏆", bg: "bg-orange-200" },
  { label: "Learning Programs", href: "#events", emoji: "🥇", bg: "bg-amber-200"  },
];

export const HACKATHON_BANNERS = [
  {
    title: "India Innovates 2026", org: "World's Biggest Youth Innovation Summit",
    tag: "₹5,00,000 Prize", bg: "from-indigo-900 via-purple-900 to-slate-900",
    accent: "bg-purple-500", span2: true,
    modeTags: ["Offline", "Free"], ctaTag: undefined,
    cardTitle: "Register Now! India Innovates 2026", cardSubtitle: "Youth Innovation Summit",
  },
  {
    title: "Brand Champion Challenge", org: "Head & Shoulders",
    tag: "Live Now", bg: "from-blue-900 via-blue-800 to-cyan-900",
    accent: "bg-cyan-400", span2: false,
    modeTags: ["Free"], ctaTag: undefined,
    cardTitle: "Brand Champion Challenge", cardSubtitle: "Head & Shoulders",
  },
  {
    title: "One Day Internship India", org: "Unstop × Shark Tank",
    tag: "Register Now", bg: "from-slate-900 via-slate-800 to-blue-900",
    accent: "bg-yellow-400", span2: false,
    modeTags: ["Online", "Free"], ctaTag: "Apply Now",
    cardTitle: "One Day Internship India ft. Shark Tank", cardSubtitle: "Unstop",
  },
  {
    title: "Creator Circuit", org: "EuroGrip",
    tag: "Meet MS Dhoni", bg: "from-red-900 via-red-800 to-orange-900",
    accent: "bg-red-400", span2: false,
    modeTags: [], ctaTag: "Participate Now",
    cardTitle: "Eurogrip – Creator Circuit", cardSubtitle: "EuroGrip",
  },
  {
    title: "Creator Circuit Season 1", org: "EuroGrip",
    tag: "Meet MS Dhoni", bg: "from-red-900 via-red-800 to-orange-900",
    accent: "bg-red-400", span2: false,
    modeTags: [], ctaTag: "Participate Now",
    cardTitle: "Eurogrip – Creator Circuit Season 1", cardSubtitle: "EuroGrip",
  },
  {
    title: "Creator Circuit World Series", org: "EuroGrip",
    tag: "Meet MS Dhoni", bg: "from-red-900 via-red-800 to-orange-900",
    accent: "bg-red-400", span2: false,
    modeTags: [], ctaTag: "Participate Now",
    cardTitle: "Eurogrip – Creator Circuit World Series", cardSubtitle: "EuroGrip",
  },
  {
    title: "Developer Circuit", org: "EuroGrip",
    tag: "Meet MS Dhoni", bg: "from-red-900 via-red-800 to-orange-900",
    accent: "bg-red-400", span2: false,
    modeTags: [], ctaTag: "Participate Now",
    cardTitle: "Eurogrip – Developer Circuit", cardSubtitle: "EuroGrip",
  },
];

export const INTERNSHIPS = [
  {
    title: "Campus Ambassador Internship",
    company: "Aptisure Learning Pvt. Ltd.",
    location: "Remote",
    stipend: "15K–20K/month",
    duration: "3 months",
    logo: "AP",
    logoColor: "bg-blue-100 text-blue-700",
    postedOn: "linkedin" as const,
    verified: true,
    postedAt: "2 days ago",
  },
  {
    title: "Webflow Specialist Internship",
    company: "Ballistic Media",
    location: "Remote",
    stipend: "10K–12K/month",
    duration: "6 months",
    logo: "BM",
    logoColor: "bg-purple-100 text-purple-700",
    postedOn: "unstop" as const,
    verified: true,
    postedAt: "1 day ago",
  },
  {
    title: "Founder's Office Internship",
    company: "Reve Cult Tech PVT. Ltd.",
    location: "Delhi NCR",
    stipend: "Unpaid",
    duration: "2 months",
    logo: "RC",
    logoColor: "bg-orange-100 text-orange-700",
    postedOn: "careers" as const,
    verified: false,
    postedAt: "5 days ago",
  },
];

export const JOBS = [
  {
    title: "Frontend Engineer",
    company: "Razorpay",
    location: "Bengaluru",
    salary: "8–12 LPA",
    jobType: "Full-time",
    experience: "1–3 yrs",
    logo: "RZ",
    logoColor: "bg-blue-100 text-blue-700",
    postedOn: "linkedin" as const,
    verified: true,
    postedAt: "3 days ago",
  },
  {
    title: "Product Designer",
    company: "CRED",
    location: "Remote",
    salary: "12–18 LPA",
    jobType: "Full-time",
    experience: "2–4 yrs",
    logo: "CR",
    logoColor: "bg-rose-100 text-rose-700",
    postedOn: "naukri" as const,
    verified: true,
    postedAt: "1 day ago",
  },
  {
    title: "Backend Developer",
    company: "Groww",
    location: "Bengaluru",
    salary: "6–10 LPA",
    jobType: "Full-time",
    experience: "0–2 yrs",
    logo: "GW",
    logoColor: "bg-green-100 text-green-700",
    postedOn: "careers" as const,
    verified: false,
    postedAt: "Today",
  },
];

export const HACKATHONS = [
  {
    title: "HackWithInfy 2026",
    org: "Infosys",
    tag: "Open",
    prize: "₹3,00,000",
    deadline: "Apr 15",
    participants: "12,000+",
    teamSize: "2–4 members",
    categories: ["Web Dev", "AI/ML", "Cloud"],
    postedOn: "unstop" as const,
    verified: true,
    postedAt: "4 days ago",
  },
  {
    title: "Smart India Hackathon",
    org: "Ministry of Education",
    tag: "Registering",
    prize: "₹1,00,000",
    deadline: "May 1",
    participants: "50,000+",
    teamSize: "3–6 members",
    categories: ["Data Science", "GovTech", "ML"],
    postedOn: "careers" as const,
    verified: true,
    postedAt: "1 week ago",
  },
  {
    title: "Code for Good",
    org: "J.P. Morgan",
    tag: "Closing Soon",
    prize: "PPO Offer",
    deadline: "Mar 30",
    participants: "8,000+",
    teamSize: "Individual",
    categories: ["FinTech", "Web Dev"],
    postedOn: "linkedin" as const,
    verified: true,
    postedAt: "2 days ago",
  },
];

export const EVENTS = [
  {
    title: "Resume Masterclass",
    org: "CareerUnlock",
    tag: "Free",
    date: "Mar 12, 2026",
    mode: "Online",
    seats: "500",
    categories: ["Career", "Resume"],
    postedOn: "unstop" as const,
    verified: true,
    postedAt: "Today",
  },
  {
    title: "Startup Networking Night",
    org: "Headstart Network",
    tag: "Paid",
    date: "Mar 18, 2026",
    mode: "Delhi NCR",
    seats: "120",
    categories: ["Networking", "Startups"],
    postedOn: "linkedin" as const,
    verified: true,
    postedAt: "3 days ago",
  },
  {
    title: "AI Career Summit",
    org: "Analytics Vidhya",
    tag: "Free",
    date: "Apr 2, 2026",
    mode: "Online",
    seats: "2000",
    categories: ["AI/ML", "Data Science", "Career"],
    postedOn: "careers" as const,
    verified: false,
    postedAt: "5 days ago",
  },
];